package com.example.sai_h.labex;

import android.graphics.Color;
import android.os.Bundle;
import android.support.annotation.Nullable;
import android.support.v4.app.Fragment;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;

public class FontColorFragment extends Fragment {
    View v;
    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        /*ViewGroup to be inflated into the activity
          This is not necessary in activity. In activity it is autogenerated
          super.onCreate(savedInstanceState);
          setContentView(R.layout.your_activity);
         */
        v = inflater.inflate(R.layout.fragment_font_color,container,false);
        return v; //Returns the Viewgroup to the activity class for inflation
    }

    @Override
    public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        //All the view elements of the fragment are identified using the viewgroup. Here viewgroup is stored in variable v
        final TextView t = (TextView)v.findViewById(R.id.txt);
        v.findViewById(R.id.red).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                t.setBackgroundColor(Color.RED);
            }
        });
        v.findViewById(R.id.green).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                t.setBackgroundColor(Color.GREEN);
            }
        });
        v.findViewById(R.id.yellow).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                t.setBackgroundColor(Color.YELLOW);
            }
        });
    }
}
