package com.example.sai_h.labex;


import android.graphics.Typeface;
import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import com.example.sai_h.labex.utils.FontChanger;


/**
 * A simple {@link Fragment} subclass.
 */
public class HomeFragment extends Fragment {


    public HomeFragment() {
        // Required empty public constructor
    }


    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        /*ViewGroup to be inflated into the activity
          This is not necessary in activity. In activity it is autogenerated
          super.onCreate(savedInstanceState);
          setContentView(R.layout.your_activity);
         */
        View view=inflater.inflate(R.layout.fragment_home, container, false);

        Typeface bold = Typeface.createFromAsset(getActivity().getAssets(),"fonts/product_sans_bold.ttf");
        FontChanger boldFontChanger = new FontChanger(bold);
        boldFontChanger.replaceFonts((ViewGroup) view);
        return view;
    }

}
