package com.example.sai_h.labex;


import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;


/**
 * A simple {@link Fragment} subclass.
 */
public class HomeFragment extends Fragment {


    public HomeFragment() {
        // Required empty public constructor
    }


    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        /*ViewGroup to be inflated into the activity
          This is not necessary in activity. In activity it is autogenerated
          super.onCreate(savedInstanceState);
          setContentView(R.layout.your_activity);
         */
        return inflater.inflate(R.layout.fragment_home, container, false);
    }

}
